const publications = {
      state: {
            publications: {
                  titre: "Publications",
                  type: "list-paragraphe",
                  content: [
                        [
                              {
                                    text: "Kasdallah, I., Ghorab, MA, Jebbar, O., Sellami, K., Sayagh, M., Ouni, A., Saied, MA., (2026)."
                              },
                              {
                                    text: "MLStractor: LLM-Powered Search-Based Monolith-To-Microservice Decomposition,",
                                    link: "",
                              },
                              {
                                    text: "Accepted for publication at the 18th Symposium on Search-Based Software Engineering 2026 (SSBSE 2026)."
                              }
                        ],
                        [
                              {
                                    text: "Arabat, A., Sayagh, M., (2026)."
                              },
                              {
                                    text: "Toward Instructions-as-Code: Understanding the Impact of Instruction Files on Agentic Pull Requests,",
                                    link: "",
                              },
                              {
                                    text: "Accepted for publication at the Mining Software Repositories (MSR) conference - mining challenge."
                              }
                        ],
                        [
                              {
                                    text: "Abujadallah, M., Arabat, A., Sayagh, M., (2026)."
                              },
                              {
                                    text: "Understanding the Rejection of Fixes Generated by Agentic Pull Requests - Insights from the AIDev Dataset,",
                                    link: "",
                              },
                              {
                                    text: "Accepted for publication at the Mining Software Repositories (MSR) conference - mining challenge."
                              }
                        ],
                        [
                              {
                                    text: "Ibrahmi, EZ., Ouni, A., Sayagh, M., Saied, MA., (2026)."
                              },
                              {
                                    text: "Characterizing Self-Admitted Technical Debt Generated by AI Coding Agents,",
                                    link: "",
                              },
                              {
                                    text: "Accepted for publication at the Mining Software Repositories (MSR) conference - mining challenge."
                              }
                        ],
                        [
                              {
                                    text: "Khelifi, J., Begoug, M., Ouni, A., Sayagh, M., Saied, MA., (2026)."
                              },
                              {
                                    text: "On the Reliability of Agentic AI in Continuous Integration Pipelines,",
                                    link: "",
                              },
                              {
                                    text: "Accepted for publication at the Mining Software Repositories (MSR) conference - mining challenge."
                              }
                        ],
                        [
                              {
                                    text: "Belwafi, K., Sayagh, M., Ouni, A., (2026)."
                              },
                              {
                                    text: "Code-Level Challenges and Opportunities in Hardware Description Languages: Insights from StackOverflow Discussions,",
                                    link: "",
                              },
                              {
                                    text: "Accepted for publication in the Integration journal."
                              }
                        ],
                        [
                              {
                                    text: "Bessghaier, N., Ouni, A., Sayagh, M., Mkaouer, MW., (2025)."
                              },
                              {
                                    text: "A Search-Based File Recommendation Approach for Infrastructure-as-Code Evolution,",
                                    link: "",
                              },
                              {
                                    text: "Accepted for publication in Journal of Systems and Software (JSS)."
                              }
                        ],
                        [
                              {
                                    text: "Aidasso, H., Sayagh, M., Bordeleau, F., (2025)."
                              },
                              {
                                    text: "A Systematic Literature Review on Build Optimization,",
                                    link: "",
                              },
                              {
                                    text: "Accepted in the ACM Computing Surveys (CSUR) journal."
                              }
                        ],
                        [
                              {
                                    text: "Feki, H., Abdellatif, M., Sayagh, M., (2025)."
                              },
                              {
                                    text: "An Empirical Study on Hugging Face Trends, Topics and Challenges on Stack Overflow,",
                                    link: "",
                              },
                              {
                                    text: "Accepted for publication in the IEEE Computers, Software, and Applications Conference (COMPSAC 2025)."
                              }
                        ],
                        [
                              {
                                    text: "Bessghaier, N., Ouni, A., Chouchen, M., Sayagh, M., Mkaouer, MW., (2025)."
                              },
                              {
                                    text: "Towards Understanding Code Review Practices for Infrastructure-as-Code: An Empirical Study on OpenStack Projects,",
                                    link: "",
                              },
                              {
                                    text: "Accepted in the Empirical Software Engineering (EMSE) journal."
                              }
                        ],
                        [
                              {
                                    text: "Soltaniani, F., Ghafari, M., Sayagh, M., (2025)."
                              },
                              {
                                    text: "Security Bug Report Prediction Within and Across Projects: A Comparative Study of BERT and Random Forest,",
                                    link: "",
                              },
                              {
                                    text: "Accepted in the 21st International Conference on Predictive Models and Data Analytics in Software Engineering (PROMISE 2025)."
                              }
                        ],
                        [
                              {
                                    text: "Khelifi, J., Benzina, Y., Chouchen, M., Ouni, A., Sayagh, M., Bouktif, S., (2025)."
                              },
                              {
                                    text: "GHAminer: An Open Source Tool to Extract GitHub Actions Build Metrics,",
                                    link: "",
                              },
                              {
                                    text: "Accepted in The International Conference on Software Analysis, Evolution and Reengineering (SANER 2025) - Tool demo track."
                              }
                        ],
                        [
                              {
                                    text: "Bouaziz, A., Saied, MA., Sayagh, M., Ouni, A., and Mkaouer, MW., (2025)."
                              },
                              {
                                    text: "An Empirical Study on Microservices Deployment Trends, Topics and Challenges in Stack Overflow,",
                                    link: "",
                              },
                              {
                                    text: "Accepted in The International Conference on Software Analysis, Evolution and Reengineering (SANER 2025)."
                              }
                        ],
                        [
                              {
                                    text: "Kansab, S., Sayagh, M., Bordeleau, F., Tizghadam, A., (2025)."
                              },
                              {
                                    text: "Understanding the Amount of Changes Required for Merge Request Acceptance: An Empirical Study,",
                                    link: "",
                              },
                              {
                                    text: "Accepted in the 16th International Conference on Software Engineering and Service Science (ICSESS 2025)."
                              }
                        ],
                        [
                              {
                                    text: "Ouatiti, YE., Sayagh M., Kerzazi, N., Adams, B., Hassan, AE., (2024)."
                              },
                              {
                                    text: "The impact of Concept drift and Data leakage on Log Level Prediction Models,",
                                    link: "https://msayagh.github.io/pdf/Youssef-EMSE-2024.pdf",
                              },
                              {
                                    text: "Empirical Software Engineering (EMSE)."
                              }
                        ], 
                        [
                              {
                                    text: "Harbaoui, F., Sayagh, M., Abdalkareem, R., (2024). "
                              },
                              {
                                    text: "On the Impact of Draft Pull Requests on Accelerating Feedback,",
                                    link: "https://msayagh.github.io/pdf/Firas-ICSME-2024.pdf",
                              },
                              {
                                    text: "Accepted in The International Conference on Software Maintenance and Evolution (ICSME 2024)."
                              }
                        ], 
                        [
                              {
                                    text: "Arabat, A., Sayagh, M., (2024). "
                              },
                              {
                                    text: "An Empirical Study on Cross-component Dependent Changes - A case Study on the Components of OpenStack,",
                                    link: "https://msayagh.github.io/pdf/Arabat-EMSE-2024.pdf",
                              },
                              {
                                    text: "Empirical Software Engineering (EMSE)."
                              }
                        ], 
                        [
                              {
                                    text: "Bessghaier, N., Begoug, M., Mebarki, C., Ouni, A., Sayagh, M. and Mkaouer, MW., (2024). (To appear). "
                              },
                              {
                                    text: "On the Prevalence, Co-occurrence, and Impact of Infrastructure-as-Code Smells,",
                                    link: "",
                              },
                              {
                                    text: "Published in the IEEE International Conference on Software Analysis, Evolution and Reengineering (SANER 2024)."
                              }
                        ],
                        [
                              {
                                    text: "Batoun, MA., Sayagh, M., Ouni, A., (2024). (To appear). "
                              },
                              {
                                    text: "How Much Logs Does My Source Code File Need? Learning to Predict the Density of Logs,",
                                    link: "",
                              },
                              {
                                    text: "Accepted in the International Conference on Evaluation and Assessment in Software Engineering (EASE 2024)."
                              }
                        ],
                        [
                              {
                                    text: "Batoun, MA., Sayagh, M., Aghili, R., Ouni, A., Li, H., (2024). "
                              },
                              {
                                    text: "A Literature Review and Existing Challenges on Software Logging Practices - From the Creation to the Analysis of Software Logs,",
                                    link: "https://msayagh.github.io/pdf/Batoun-EMSE-2024.pdf",
                              },
                              {
                                    text: "Empirical Software Engineering (EMSE)."
                              }
                        ],
                        [
                              {
                                    text: "Chen, J., Ding, Z., Tang, Y., Sayagh, M., Li, H., Adams, B., Shang, W., (2023). "
                              },
                              {
                                    text: "IoPV: On Inconsistent Option Performance Variations,",
                                    link: "https://msayagh.github.io/pdf/Jinfu-FSE-2023.pdf",
                              },
                              {
                                    text: "Proceedings of the 31st ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering (ESEC/FSE 2023)."
                              }
                        ],
                        [
                              {
                                    text: "Bessghaier, N., Sayagh, M., Ouni, A., Mkaouer, MW., (2023). "
                              },
                              {
                                    text: "What Constitutes the Deployment and Run-time Configuration System? An Empirical Study on OpenStack Projects,",
                                    link: "https://msayagh.github.io/pdf/Narjess-TOSEM-2023.pdf",
                              },
                              {
                                    text: "ACM Transactions on Software Engineering and Methodology (TOSEM)."
                              }
                        ],
                        [
                              {
                                    text: "Batoun, MA., Yung, KL., Tian, Y., Sayagh M., (2023). "
                              },
                              {
                                    text: "An Empirical Study on Github Pull Requests' Reactions,",
                                    link: "https://msayagh.github.io/pdf/Batoun-TOSEM-2023.pdf",
                              },
                              {
                                    text: "ACM Transactions on Software Engineering and Methodology (TOSEM)."
                              }
                        ],
                        [
                              {
                                    text: "Lin, J., Sayagh M., Hassan, AE., (2022). "
                              },
                              {
                                    text: "The Co-evolution of the WordPress Platform and its Plugins,",
                                    link: "https://msayagh.github.io/pdf/TOSEM_2022_plugins.pdf",
                              },
                              {
                                    text: "ACM Transactions on Software Engineering and Methodology (TOSEM)."
                              }
                        ],
                        [
                              {
                                    text: "Ouatiti, YE., Sayagh M., Kerzazi, N., Hassan, AE., (2022)."
                              },
                              {
                                    text: "An Empirical Study on Log Level Prediction for Multi-component Systems,",
                                    link: "https://msayagh.github.io/pdf/TSE_2022_log_multicomp.pdf",
                              },
                              {
                                    text: "Transactions on Software Engineering (TSE)."
                              }
                        ],
                        [
                              {
                                    text: "Ibrahim, MH., Sayagh M., Hassan, AE., (2021)."
                              },
                              {
                                    text: "A Study of How Docker Compose is Used to Compose Multi-component Systems,",
                                    link: "https://msayagh.github.io/pdf/EMSE_2021_docker_compose.pdf",
                              },
                              {
                                    text: "Empirical Software Engineering (EMSE)."
                              }
                        ],
                        [
                              {
                                    text: "Yao, K., Sayagh M., Weiyi, S., Hassan, AE., (2021)."
                              },
                              {
                                    text: "Improving state-of-the-art compression techniques for log management tools,",
                                    link: "https://msayagh.github.io/pdf/LogBlock_TSE_2021.pdf",
                              },
                              {
                                    text: "Transactions on Software Engineering (TSE)."
                              }
                        ],
                        [
                              {
                                    text: "Lyu, Y., Li, H., Sayagh, M., Jiang, ZM., Hassan, AE. (2021)."
                              },
                              {
                                    text: "An Empirical Study of the Impact of Data Splitting Decisions on the Performance of AIOps Solutions,",
                                    link: "https://msayagh.github.io/pdf/TOSEM2021.pdf",
                              },
                              {
                                    text: "ACM Transactions on Software Engineering and Methodology (TOSEM)."
                              }
                        ],
                        [
                              {
                                    text: "Ibrahim, MH., Sayagh M., Hassan, AE.(2020)."
                              },
                              {
                                    text: "Too many images on DockerHub! How different are images for the same system?",
                                    link: "https://msayagh.github.io/pdf/EMSE2020_Dockerhub.pdf",
                              },
                              {
                                    text: "Empirical Software Engineering (EMSE)."
                              }                        ],
                        [
                              {
                                    text: "Sayagh M., Hassan, AE. (2020)."
                              },
                              {
                                    text: "ConfigMiner: Identifying the Appropriate Configuration Options for Config-related User Questions by Mining Online Forums,",
                                    link: "https://msayagh.github.io/pdf/TSE2020_configminer.pdf",
                              },
                              {
                                    text: "Transactions on Software Engineering (TSE)."
                              }
                        ],
                        [
                              {
                                    text: "Li, H., Shang, W., Adams, B., Sayagh M., Hassan, AE. (2020)."
                              },
                              {
                                    text: "A Qualitative Study of the Benefits and Costs of Logging from Developers' Perspectives,",
                                    link: "https://msayagh.github.io/pdf/TSE2020_logging.pdf",
                              },
                              {
                                    text: "Transactions on Software Engineering (TSE)."
                              }                        ],
                        [
                              {
                                    text: "Lee D., Rajbahadur, GK., Lin D., Sayagh M., Bezemer, CP., Hassan, AE. (2020)."
                              },
                              {
                                    text: "An Empirical Study of the Characteristics of Popular Minecraft Mods,",
                                    link: "https://msayagh.github.io/pdf/EMSE2020_mods.pdf",
                              },
                              {
                                    text: "Empirical Software Engineering (EMSE)."
                              }
                        ],
                        [
                              {
                                    text: "Sayagh, M., Kerazi, N., Petrillo, F., Bennani, K., and Adams, B. (2020)."
                              },
                              {
                                    text: "What should your run-time configuration framework do to help developers?",
                                    link: "https://msayagh.github.io/pdf/EMSE2020_config2code.pdf",
                              },
                              {
                                    text: "Empirical Software Engineering (EMSE)."
                              }
                        ],
                        [
                              {
                                    text: "Sayagh, M., Kerazi, N., Adams, B. And Petrillo, F.(2018)."
                              },
                              {
                                    text: "Software configuration engineering in practice - interviews, survey, and systematic literature review",
                                    link: "https://msayagh.github.io/pdf/TSE2018.pdf",
                              },
                              {
                                    text: "Transactions on software engineering(TSE)."
                              }
                        ],
                        [
                              {
                                    text: "Sayagh, M., Dong, Z., Andrzejak, A., And Adams, B.(2017)."
                              },
                              {
                                    text: "Does the choice of configuration framework matter for developers?",
                                    link: "https://msayagh.github.io/pdf/SCAM2017.pdf",
                              },
                              {
                                    text: ", in proceedings of the 17th ieee international working conference on source code analysis and manipulation, scam (shanghai, china). (acceptance ratio: 14/31=45%) "
                              }
                        ],
                        [
                              {
                                    text: "Sayagh, M., Kerzaki, N., Adams, B.(2017)."
                              },
                              {
                                    text: "On cross-stack configuration errors",
                                    link: "https://msayagh.github.io/pdf/ICSE2017.pdf",

                              },
                              {
                                    text: ", in proceedings of the 39th international conference on software engineering, icse (buenos aires, argentina). (acceptance ratio: 68/398=17%)"
                              }
                        ],
                        [
                              {
                                    text: "Hassan, S., King, Z., Hafiz, M.,Sayagh, M., Adams, B. And Hindle, A. (2016). "
                              },
                              {
                                    text: "Energy profiles of java collections classes, ",
                                    link: "https://msayagh.github.io/pdf/ICSE2016.pdf",

                              },
                              {
                                    text: "in proceedings of the 38th international conference on software engineering, ICSE (Austin, tx, us). (acceptance ratio: 101/530=19%)"
                              },
                              {
                                    text: "(ACM SIGSOFT Distinguished Paper Award)"
                              }
                        ],
                        [
                              {
                                    text: "Sayagh, M. 'tracking misconfiguration errors in multi - layered architecture systems'. Doctoral symposium track of the 23rd ieee international conference on software analysis, evolution, and reengineering (saner 2016)."
                              }
                        ],
                        [
                              {
                                    text: "Sayagh, M. And Adams, B. (2015)."
                              },
                              {
                                    text: "Multi-layer software configuration - empirical study on wordpress",
                                    link: "https://msayagh.github.io/pdf/SCAM2015.pdf",

                              },
                              {
                                    text: ", in proceedings of the 15th ieee international working conference on source code analysis and manipulation, scam (bremen, germany). (acceptance ratio: 24/68=35%) "
                              }
                        ],
                  ],
            },
      },
      getters: {
            GET_PUBLICATIONS: (state, payload) => state.publications,
      }
}

export default publications;
